### all films [✔]
GET http://localhost:5555/films

### get by genre [✔]
GET http://localhost:5555/films?genre=sci-fi

### get by id [✔]
GET http://localhost:5555/films/64f89a1065254d2bb4e946f5

### create a film [✔]
POST http://localhost:5555/films
Content-Type: application/json

{
  "title": "Blade Runner",
  "year": 1982,
  "director": "Ridley Scott",
  "duration": 117,
  "poster": "https://m.media-amazon.com/images/M/MV5BMTYwNjQxMjA4M15BMl5BanBnXkFtZTYwMDI2NTg3._V1_.jpg",
  "plot": "A blade runner must pursue and terminate four replicants who stole a ship in space, and have returned to Earth to find their creator.",
  "trailer": "http://cambiar.com",
  "genre": ["Sci-Fi", "Thriller"],
  "rate": 8.1
}


### update  [✔]
PATCH http://localhost:5555/films/64f89a1065254d2bb4e946f5
Content-Type: application/json

{
  "poster": "https://m.media-amazon.com/images/I/71H0Ynb-vzL._AC_SL1000_.jpg",
  "trailer": "https://www.youtube.com/watch?v=OL5dD-EwcaU"
}

### delete [✔]
delete http://localhost:5555/films/64f7a8710c56fec05cde25ec
